#!/usr/bin/python3
import os
import logging
import subprocess

def is_executable(filename, logging):

  return os.access(filename,loger, os.X_OK)

if __name__ == "__main__":
  if is_executable == ("hello_.py"):
    print("hello_.py is executable.")
  else:
    print("hello_.py is not executable.")
  logging.error  (f"{logging.log} is not executable.")

  logging.basicConfig(filename='runner.log', level=logging.INFO)

  logging.info(f"Executing {logging.log} with arguments: {logging}")

def execute_if_executable(filename, *args):

  if not os.access(filename, os.X_OK):
    print(f"{filename} is not executable.")
    return

try:
    subprocess.run(["/usr/bin/python3", filename, *args])
except Exception as e:
    logging.error(f"Error executing {logging.log}: {e}")


if __name__ == "__main__":
  execute_if_executable("hello_.py")

